### ISSUE TITLE
PropFrame.SetModifiers 

### ISSUE THREAD

**Issue by iartkore** [marcellosgamb/SIMPLEX#3]
**Describe the bug**
PropFrame.SetModifiers node in SRTUCTURE/Dynamo_for_Etabs_2017 is constructed with "Value" variable as an output, while it is an input variable

![PropFrame SetModifiers](https://user-images.githubusercontent.com/47659986/60760893-b7237600-9ff1-11e9-8d33-fcb3b4dbec80.png)

**Steps to Reproduce**
I was trying to alter property modifiers of existing sections

**Expected behavior**
"Value" variable should be constructed as an input

int SetModifiers(
	string Name,
	ref double[] Value
)

**My setup**
- Operating System: win10pro 
- Dynamo version: 2.1.0.7500
- Simplex version: 2019.2.1
- Revit version: 2020

**Comment by marcellosgamb** [comment]
Thx
Will adjust
________________________________

**Comment by marcellosgamb** [comment]
fixed see latest simplex package and image 
![image](https://user-images.githubusercontent.com/6132497/60765047-c4b81a80-a048-11e9-9926-f24c3d085ea8.png)

**Comment by iartkore** [comment]
This is great! It is getting more than awesome. Thank you!
